import Foundation

/// Deterministic generator for `wiki/index.md` — the content catalog the
/// model reads to know what the wiki contains (Karpathy's LLM-wiki pattern).
///
/// The index is *derived* markdown, same class of artifact as
/// `index.sqlite`: regenerated by the app after every reindex, never
/// maintained by the model. A catalog that rots is worse than none, and
/// small local models can't be trusted to keep it current.
enum IndexPageGenerator {

    /// Page ids that never appear in the catalog: the index itself, the
    /// operations journal, and the conventions file.
    static let reservedIDs: Set<String> = ["index", "log", "agents"]

    struct Entry {
        let id: String
        let title: String
        let summary: String?
    }

    /// Pure: entries in, full `index.md` content out. Entries are sorted
    /// by title (then id) so the output is stable across runs — the
    /// caller compares bytes to decide whether to rewrite the file.
    static func generate(entries: [Entry]) -> String {
        let listed = entries
            .filter { !reservedIDs.contains($0.id) }
            .sorted {
                ($0.title.lowercased(), $0.id) < ($1.title.lowercased(), $1.id)
            }

        var lines: [String] = [
            "---",
            "id: index",
            "title: Index",
            "type: index",
            "---",
            "",
            "> Catalogue généré automatiquement — ne pas modifier à la main.",
            ""
        ]
        if listed.isEmpty {
            lines.append("*Le wiki est vide.*")
        } else {
            for entry in listed {
                if let summary = entry.summary, !summary.isEmpty {
                    lines.append("- [[\(entry.id)|\(entry.title)]] — \(summary)")
                } else {
                    lines.append("- [[\(entry.id)|\(entry.title)]]")
                }
            }
        }
        return lines.joined(separator: "\n") + "\n"
    }
}
